### ISSUE TITLE
[Request] Add Svelte logos by mkpoli and styx

### ISSUE THREAD

**Issue by mkpoli** [alfonsusac/service-title-logo#1]
So styx and I also made svelte logo much earlier

https://x.com/mkpoli/status/1781931713939288337
https://x.com/styxpilled/status/1781565832251719868
https://x.com/styxpilled/status/1781643208130216015

**Comment by mkpoli** [comment]
For my version I released the svg in Gist but I also plan to make more so maybe I will clean it up and release them with CC

**Comment by mkpoli** [comment]
I cleaned up my Svelte logo and put it into a public repository released as CC0
https://github.com/mkpoli/VTuber-Styled-Logos

**Comment by alfonsusac** [comment]
> For my version I released the svg in Gist but I also plan to make more so maybe I will clean it up and release them with CC

It would be nice if you have them in a github repository so I can scrape them automatically 👀

**Comment by mkpoli** [comment]
> > For my version I released the svg in Gist but I also plan to make more so maybe I will clean it up and release them with CC
> 
> It would be nice if you have them in a github repository so I can scrape them automatically 👀

I did exactly that:

> I cleaned up my Svelte logo and put it into a public repository released as CC0
> https://github.com/mkpoli/VTuber-Styled-Logos

_Originally posted by @mkpoli in https://github.com/alfonsusac/service-title-logo/issues/1#issuecomment-2080367673_

**Comment by alfonsusac** [comment]
Thanks for the effort of putting it in GitHub! <3

**Comment by alfonsusac** [comment]
Added @mkpoli
